cp -r /Volumes/LaCie/multimedia/video/movie/caligula /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/Glory /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/danceWithWolfs /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/JungleFever /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/1492ChristopheColomb /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/lesEvades /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/breaveheart /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/Underground /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/amistad /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheBigLebowski /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/BoogieNights /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ColdMountain /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/RequiemForADream /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/OBrother /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/snatch /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/RoadToPerdition /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ManOnFire /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/GirlWithAPearlEarring /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/thePassionOfTheChrist /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/JeuxDEnfants /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheBourneSupremacy /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LovelyBones /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LiveAndBecome /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/sinCity /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MillionDollarBaby /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheSecretLifeOfBees /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/300 /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/JacquouLeCroquant /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheBourneUltimatum /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LesSeptjoursduTalion /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/littleMissSunshine /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LesPassagers /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/InsideMan /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ThePursuitOfHappyness /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LesSimpsons /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/juno /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ThingsWeLostInTheFire /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/avatar /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/moliere /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LoveGourou /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theSoloist /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheKidsAreAllRight /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/smartPeople /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LePremierJourDuResteDeTaVie /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/hugoCabret /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theReader /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/Traitor /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/leLoupDeWallStreet /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/SlumdogMillionaire /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/aliceInWonderland /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MiracleAtStAnna /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/invictus /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/jusquaToi /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/BadLieutenantPortOfCallNewOrleans /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/motherAndChild /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/cracks /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/adam /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MyNameIsKhan /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/EnterTheVoid /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/IpMan /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ItsComplicated /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LeSangDesTempliers /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/weNeedToTalkAboutKevin /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/jeLAimais /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/mademoiselleChambon /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/encoreUnBaiser /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheDarkKnightRises /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ipMan2 /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TellementProches /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/InDarkness /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/perfectSense /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/UnderTheSkin /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/conjuring /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/leHavre /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/Melancholia /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/anotherEarth /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theMaster /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/WarHorse /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theWeAndTheI /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/bendaBilili /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/ProjectX /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/terraferma /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/dictator /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theImpossible /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theArtist /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/polisse /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/pouletAuxPrunes /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/takeShelter /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/laSourceDesFemmes /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/InTheLandOfBloodAndHoney /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/OnlyLoversLeftAlive /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/tousLesSoleils /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LosColoresDeLaMontana /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MoonriseKingdom /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/AnnaKarenine /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LesFemmesDuSixiemeEtage /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/WarWitch /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/bullhead /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MoiMichelGMilliardaireMaitreDuMonde /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/TheWords /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/MetroManila /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/djangoUnchained /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/flight /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/leGrandSoir /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/alabamaMonroe /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/12yearsASlave /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/DeRouilleEtDOs /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/lEnfantDEnHaut /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/lesInfideles /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/BeastsOfTheSouthernWild /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/theBagMan /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/paulette /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/LesKaira /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/inchAllah /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/tangoLibre /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/leVenusALaFourrure /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/CommeUnLion /Volumes/wd-1To/
cp -r /Volumes/LaCie/multimedia/video/movie/jeuneEtJolie /Volumes/wd-1To/
