ls -d /Volumes/LaCie/multimedia/video/movie/caligula > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/Glory > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/danceWithWolfs > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/JungleFever > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/1492ChristopheColomb > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/lesEvades > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/breaveheart > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/Underground > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/amistad > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheBigLebowski > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/BoogieNights > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ColdMountain > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/RequiemForADream > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/OBrother > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/snatch > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/RoadToPerdition > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ManOnFire > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/GirlWithAPearlEarring > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/thePassionOfTheChrist > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/JeuxDEnfants > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheBourneSupremacy > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LovelyBones > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LiveAndBecome > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/sinCity > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MillionDollarBaby > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheSecretLifeOfBees > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/300 > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/JacquouLeCroquant > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheBourneUltimatum > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LesSeptjoursduTalion > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/littleMissSunshine > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LesPassagers > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/InsideMan > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ThePursuitOfHappyness > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LesSimpsons > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/juno > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ThingsWeLostInTheFire > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/avatar > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/moliere > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LoveGourou > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theSoloist > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheKidsAreAllRight > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/smartPeople > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LePremierJourDuResteDeTaVie > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/hugoCabret > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theReader > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/Traitor > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/leLoupDeWallStreet > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/SlumdogMillionaire > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/aliceInWonderland > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MiracleAtStAnna > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/invictus > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/jusquaToi > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/BadLieutenantPortOfCallNewOrleans > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/motherAndChild > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/cracks > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/adam > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MyNameIsKhan > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/EnterTheVoid > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/IpMan > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ItsComplicated > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LeSangDesTempliers > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/weNeedToTalkAboutKevin > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/jeLAimais > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/mademoiselleChambon > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/encoreUnBaiser > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheDarkKnightRises > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ipMan2 > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TellementProches > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/InDarkness > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/perfectSense > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/UnderTheSkin > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/conjuring > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/leHavre > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/Melancholia > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/anotherEarth > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theMaster > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/WarHorse > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theWeAndTheI > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/bendaBilili > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/ProjectX > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/terraferma > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/dictator > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theImpossible > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theArtist > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/polisse > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/pouletAuxPrunes > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/takeShelter > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/laSourceDesFemmes > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/InTheLandOfBloodAndHoney > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/OnlyLoversLeftAlive > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/tousLesSoleils > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LosColoresDeLaMontana > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MoonriseKingdom > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/AnnaKarenine > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LesFemmesDuSixiemeEtage > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/WarWitch > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/bullhead > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MoiMichelGMilliardaireMaitreDuMonde > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/TheWords > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/MetroManila > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/djangoUnchained > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/flight > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/leGrandSoir > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/alabamaMonroe > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/12yearsASlave > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/DeRouilleEtDOs > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/lEnfantDEnHaut > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/lesInfideles > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/BeastsOfTheSouthernWild > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/theBagMan > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/paulette > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/LesKaira > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/inchAllah > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/tangoLibre > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/leVenusALaFourrure > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/CommeUnLion > /dev/null
ls -d /Volumes/LaCie/multimedia/video/movie/jeuneEtJolie > /dev/null
